/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'juanramirez' at '2/14/17 9:51 PM' with Gradle 2.14.1
 *
 * @author juanramirez, @date 2/14/17 9:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
